# Generated by Django 6.0.3 on 2026-03-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='document',
            name='title',
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('uploaded', 'uploaded'), ('processing', 'processing'), ('completed', 'completed'), ('failed', 'failed')], default='uploaded', max_length=20),
        ),
    ]
